### ISSUE TITLE
Expansion horizon stimulator and bugs in _virtual

### ISSUE THREAD

**Issue by rstaehle** [nicolasmcnair/magpy#6]
Thank you for writing this comprehensive toolbox! Actually, I have two issues.

First of all, I expanded your toolbox to include the horizon stimulator by adapting the Rapid class and VirtualRapid class. Please find the corresponding repo with full documentation here: https://github.com/neuromti/ctrl-magstim_stimulators.

Secondly, the virtual class did not work for me. I haven´t created a pull request since I have customised it to the new Horizon class. However, after the following changes it performed at least for the single-pulse mode.
I replaced line 97
`if calcCRC(message[:-1]) != message[-1]:` with
`if calcCRC(bytearray(message[:-1],'latin_1')) != bytearray(message[-1],'latin_1'):`
and line 158
`returnMessage = message[0] + messageData` with
`returnMessage = bytearray(message[0] + messageData,'latin_1')`.

Additionally, some dictionary key errors occurred, which could be fixed easily by replacing (for instance in line 405) the _params in `self._params['singlePulseMode'] = 1` with `self._rapidStatus`.

Best,
Ricarda

**Comment by nicolasmcnair** [comment]
Hi Ricarda,

Apologies for the very slow response - everything has been a bit hectic
here with the start of the new semester.

I'll take a look at the Horizon class you've added ASAP. Thanks very much
for the work done on that - I had no idea it even existed! Would you be
interested in adding it directly to MagPy, or would you prefer me to link
to it instead for people using a Horizon stimulator?

And yes, the virtual class needs a bit of work ever since the newer
versions came out. I've just struggled to find time to look at it.

Kind Regards,
Nick

**Comment by caddixx** [comment]
Hi Nick,

please feel free to add the Horizon class to MagPy. Unfortunately, I do not have time to create a pull request, but let me know if you have any questions!

Best regards
Ricarda
